//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post_Metas
    {
        public string id { get; set; }
        public string postId { get; set; }
        public string keys { get; set; }
        public string content { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
