//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post_Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post_Comment()
        {
            this.Post_Comment1 = new HashSet<Post_Comment>();
        }
    
        public string id { get; set; }
        public string postId { get; set; }
        public string parentId { get; set; }
        public string title { get; set; }
        public bool published { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<System.DateTime> publishedAt { get; set; }
        public string content { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post_Comment> Post_Comment1 { get; set; }
        public virtual Post_Comment Post_Comment2 { get; set; }
        public virtual Post Post { get; set; }
    }
}
